### ISSUE TITLE
Add composer.json

### ISSUE THREAD

**Issue by amenk** [macopedia/community#4]
Can you add a composer.json for installation via composer :-)

**Comment by amenk** [comment]
Or can you add he package to TER ...

**Comment by amenk** [comment]
I will make a PR ...

**Comment by tmotyl** [comment]
merged

**Comment by amenk** [comment]
do you plan to add it also to your packagist.org account and tag a release :) ?

**Comment by tmotyl** [comment]
done :) 
https://packagist.org/packages/macopedia/community

**Comment by tmotyl** [comment]
thanks for your contributions!

**Comment by amenk** [comment]
you are welcome.
And thanks to you, too - now we do not have to fiddle around with git submodules anymore for this ext :-)
